// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using Arebis.Types;

namespace Arebis.Extensions.Tests.Arebis.Types
{
	[TestClass()]
	public class UnitExceptionsTest
	{
		[TestMethod()]
		public void SerializeDeserialize01Test()
		{
			MemoryStream buffer = new MemoryStream();

			// Make some units:
			Exception x1before = null;

			try
			{
				LengthUnits.KiloMeter.AssertCompatibility(TimeUnits.Hour);
				Assert.Fail("AssertCompatibility should have failed.");
			}
			catch (UnitConversionException ex)
			{
				x1before = ex;
			}

			// Serialize the units:
			BinaryFormatter f = new BinaryFormatter();
			f.Serialize(buffer, x1before);

			// Reset stream:
			buffer.Seek(0, SeekOrigin.Begin);

			// Deserialize units:
			BinaryFormatter g = new BinaryFormatter();
			Exception x1after = (Exception)g.Deserialize(buffer);

			buffer.Close();

			Console.WriteLine("{0}", x1before);
			Console.WriteLine("{0}", x1after);

			Assert.AreEqual(x1before.Message, x1after.Message);
		}
	}
}

