//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arebis.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSSqlModelQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSSqlModelQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arebis.Data.Properties.MSSqlModelQueries", typeof(MSSqlModelQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [name], [compatibility_level], [collation_name] FROM [master].[sys].[databases]
        ///WHERE [database_id] = DB_ID().
        /// </summary>
        internal static string GetDatabase {
            get {
                return ResourceManager.GetString("GetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///   schm.name AS TABLE_SCHEMA,
        ///   tabs.name AS TABLE_NAME,
        ///   cols.name AS COLUMN_NAME,
        ///   cols.column_id AS ORDINAL_POSITION,
        ///   typs.name AS DATA_TYPE,
        ///   cols.max_length AS DATA_MAX_LENGTH,
        ///   CASE cols.max_length
        ///   WHEN -1 THEN -1
        ///   ELSE
        ///      CASE typs.system_type_id
        ///	  WHEN 167 THEN cols.max_length
        ///	  WHEN 175 THEN cols.max_length
        ///	  WHEN 231 THEN cols.max_length / 2
        ///	  WHEN 239 THEN cols.max_length / 2
        ///	  END
        ///   END AS CHARACTER_MAX_LENGTH,
        ///   cols.precision AS NUMERIC_PRECI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetModelColumns {
            get {
                return ResourceManager.GetString("GetModelColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///   [tbs].[name] [SCHEMA_NAME],
        ///   [tab].[name] [TABLE_NAME],
        ///   [indx].[name] [INDEX_NAME],
        ///   [indx].[is_unique] [IS_UNIQUE],
        ///   [indx].[is_primary_key] [IS_PRIMARY_KEY],
        ///   [col].[name] [COLUMN_NAME],
        ///   [indc].[key_ordinal] [COLUMN_ORDINAL]
        ///FROM [sys].[schemas] [tbs],
        ///     [sys].[tables] [tab],
        ///     [sys].[indexes] [indx],
        ///	 [sys].[index_columns] [indc],
        ///	 [sys].[columns] [col]
        ///WHERE [tbs].[schema_id] = [tab].[schema_id]
        ///  AND [tab].[object_id] = [indx].[object_id]
        ///  AND [indx].[ind [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetModelIndexes {
            get {
                return ResourceManager.GetString("GetModelIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///   KCU1.CONSTRAINT_SCHEMA AS RELATIONSHIP_SCHEMA,
        ///   KCU1.CONSTRAINT_NAME AS RELATIONSHIP_NAME,
        ///   KCU2.TABLE_CATALOG AS PRIMARY_TABLE_CATALOG,
        ///   KCU2.TABLE_SCHEMA AS PRIMARY_TABLE_SCHEMA,
        ///   KCU2.TABLE_NAME AS PRIMARY_TABLE_NAME,
        ///   KCU2.COLUMN_NAME AS PRIMARY_COLUMN_NAME,
        ///   KCU1.TABLE_CATALOG AS FOREIGN_TABLE_CATALOG,
        ///   KCU1.TABLE_SCHEMA AS FOREIGN_TABLE_SCHEMA,
        ///   KCU1.TABLE_NAME AS FOREIGN_TABLE_NAME,
        ///   KCU1.COLUMN_NAME AS FOREIGN_COLUMN_NAME,
        ///   KCU1.ORDINAL_POSITION AS ORDINAL_P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetModelRelations {
            get {
                return ResourceManager.GetString("GetModelRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_SCHEMA, TABLE_NAME, CASE WHEN TABLE_TYPE = &apos;BASE TABLE&apos; THEN &apos;TABLE&apos; ELSE &apos;VIEW&apos; END AS TABLE_OR_VIEW FROM INFORMATION_SCHEMA.TABLES ORDER BY 1, 2.
        /// </summary>
        internal static string GetModelTables {
            get {
                return ResourceManager.GetString("GetModelTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT @@VERSION AS VERSION_LABEL, SERVERPROPERTY(&apos;productversion&apos;) AS VERSION_NUMBER, SERVERPROPERTY(&apos;productlevel&apos;) AS PRODUCT_LEVEL, SERVERPROPERTY(&apos;edition&apos;) AS EDITION.
        /// </summary>
        internal static string GetServerVersion {
            get {
                return ResourceManager.GetString("GetServerVersion", resourceCulture);
            }
        }
    }
}
