using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Arebis.Data.Model
{
    [Serializable]
    public class ModelColumn : TableOwnedElement
    {
        public virtual bool IsPrimaryKey { get; set; }

        public virtual bool IsAutoGenerated { get; set; }

        public virtual bool IsNullable { get; set; }

        public bool IsNonNullable {
            get { return !IsNullable; }
        }

        public virtual bool IsComputed { get; set; }

        public virtual string ComputedExpression { get; set; }

        public virtual SqlDbType DbType { get; set; }

        public virtual Type NetType { get; set; }

        public virtual string TypeName { get; set; }

        public virtual int? CharacterLength { get; set; }

        public virtual int? NumericPrecision { get; set; }

        public virtual int? NumericScale { get; set; }
    }
}
