using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using Arebis.Extensions;

namespace Arebis.Common.Tests.Arebis.Extensions
{
    [TestClass]
    public class StringExtensionTests
    {
        [TestMethod]
        public void ChunckedTests()
        {
            // Non-right-aligned:
            Assert.AreEqual("", String.Join("_", "".Chunked(0)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(0)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(0)));
            Assert.AreEqual("ABC", String.Join("_", "ABC".Chunked(0)));
            Assert.AreEqual("ABCD", String.Join("_", "ABCD".Chunked(0)));
            Assert.AreEqual("ABCDE", String.Join("_", "ABCDE".Chunked(0)));
            Assert.AreEqual("ABCDEF", String.Join("_", "ABCDEF".Chunked(0)));
            Assert.AreEqual("ABCDEFG", String.Join("_", "ABCDEFG".Chunked(0)));
            Assert.AreEqual("ABCDEFGH", String.Join("_", "ABCDEFGH".Chunked(0)));
            Assert.AreEqual("ABCDEFGHI", String.Join("_", "ABCDEFGHI".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJ", String.Join("_", "ABCDEFGHIJ".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJK", String.Join("_", "ABCDEFGHIJK".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJKL", String.Join("_", "ABCDEFGHIJKL".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJKLM", String.Join("_", "ABCDEFGHIJKLM".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJKLMN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJKLMNO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJKLMNOP", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJKLMNOPQ", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJKLMNOPQR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(0)));
            Assert.AreEqual("ABCDEFGHIJKLMNOPQRS", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(0)));
            Assert.AreEqual("", String.Join("_", "".Chunked(1)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(1)));
            Assert.AreEqual("A_B", String.Join("_", "AB".Chunked(1)));
            Assert.AreEqual("A_B_C", String.Join("_", "ABC".Chunked(1)));
            Assert.AreEqual("A_B_C_D", String.Join("_", "ABCD".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E", String.Join("_", "ABCDE".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F", String.Join("_", "ABCDEF".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G", String.Join("_", "ABCDEFG".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H", String.Join("_", "ABCDEFGH".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I", String.Join("_", "ABCDEFGHI".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J", String.Join("_", "ABCDEFGHIJ".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K", String.Join("_", "ABCDEFGHIJK".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L", String.Join("_", "ABCDEFGHIJKL".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M", String.Join("_", "ABCDEFGHIJKLM".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N", String.Join("_", "ABCDEFGHIJKLMN".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O_P", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O_P_Q", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O_P_Q_R", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(1)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O_P_Q_R_S", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(1)));
            Assert.AreEqual("", String.Join("_", "".Chunked(2)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(2)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(2)));
            Assert.AreEqual("AB_C", String.Join("_", "ABC".Chunked(2)));
            Assert.AreEqual("AB_CD", String.Join("_", "ABCD".Chunked(2)));
            Assert.AreEqual("AB_CD_E", String.Join("_", "ABCDE".Chunked(2)));
            Assert.AreEqual("AB_CD_EF", String.Join("_", "ABCDEF".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_G", String.Join("_", "ABCDEFG".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH", String.Join("_", "ABCDEFGH".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_I", String.Join("_", "ABCDEFGHI".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ", String.Join("_", "ABCDEFGHIJ".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_K", String.Join("_", "ABCDEFGHIJK".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL", String.Join("_", "ABCDEFGHIJKL".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_M", String.Join("_", "ABCDEFGHIJKLM".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN_O", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN_OP", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN_OP_Q", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN_OP_QR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(2)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN_OP_QR_S", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(2)));
            Assert.AreEqual("", String.Join("_", "".Chunked(3)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(3)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(3)));
            Assert.AreEqual("ABC", String.Join("_", "ABC".Chunked(3)));
            Assert.AreEqual("ABC_D", String.Join("_", "ABCD".Chunked(3)));
            Assert.AreEqual("ABC_DE", String.Join("_", "ABCDE".Chunked(3)));
            Assert.AreEqual("ABC_DEF", String.Join("_", "ABCDEF".Chunked(3)));
            Assert.AreEqual("ABC_DEF_G", String.Join("_", "ABCDEFG".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GH", String.Join("_", "ABCDEFGH".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI", String.Join("_", "ABCDEFGHI".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_J", String.Join("_", "ABCDEFGHIJ".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JK", String.Join("_", "ABCDEFGHIJK".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JKL", String.Join("_", "ABCDEFGHIJKL".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_M", String.Join("_", "ABCDEFGHIJKLM".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_MN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_MNO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_MNO_P", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_MNO_PQ", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_MNO_PQR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(3)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_MNO_PQR_S", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(3)));
            Assert.AreEqual("", String.Join("_", "".Chunked(4)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(4)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(4)));
            Assert.AreEqual("ABC", String.Join("_", "ABC".Chunked(4)));
            Assert.AreEqual("ABCD", String.Join("_", "ABCD".Chunked(4)));
            Assert.AreEqual("ABCD_E", String.Join("_", "ABCDE".Chunked(4)));
            Assert.AreEqual("ABCD_EF", String.Join("_", "ABCDEF".Chunked(4)));
            Assert.AreEqual("ABCD_EFG", String.Join("_", "ABCDEFG".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH", String.Join("_", "ABCDEFGH".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_I", String.Join("_", "ABCDEFGHI".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJ", String.Join("_", "ABCDEFGHIJ".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJK", String.Join("_", "ABCDEFGHIJK".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJKL", String.Join("_", "ABCDEFGHIJKL".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJKL_M", String.Join("_", "ABCDEFGHIJKLM".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJKL_MN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJKL_MNO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJKL_MNOP", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJKL_MNOP_Q", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJKL_MNOP_QR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(4)));
            Assert.AreEqual("ABCD_EFGH_IJKL_MNOP_QRS", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(4)));
            Assert.AreEqual("", String.Join("_", "".Chunked(5)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(5)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(5)));
            Assert.AreEqual("ABC", String.Join("_", "ABC".Chunked(5)));
            Assert.AreEqual("ABCD", String.Join("_", "ABCD".Chunked(5)));
            Assert.AreEqual("ABCDE", String.Join("_", "ABCDE".Chunked(5)));
            Assert.AreEqual("ABCDE_F", String.Join("_", "ABCDEF".Chunked(5)));
            Assert.AreEqual("ABCDE_FG", String.Join("_", "ABCDEFG".Chunked(5)));
            Assert.AreEqual("ABCDE_FGH", String.Join("_", "ABCDEFGH".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHI", String.Join("_", "ABCDEFGHI".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ", String.Join("_", "ABCDEFGHIJ".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_K", String.Join("_", "ABCDEFGHIJK".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_KL", String.Join("_", "ABCDEFGHIJKL".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_KLM", String.Join("_", "ABCDEFGHIJKLM".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_KLMN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_KLMNO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_KLMNO_P", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_KLMNO_PQ", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_KLMNO_PQR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(5)));
            Assert.AreEqual("ABCDE_FGHIJ_KLMNO_PQRS", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(5)));

            // Right-aligned:
            Assert.AreEqual("", String.Join("_", "".Chunked(0, true)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(0, true)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(0, true)));
            Assert.AreEqual("ABC", String.Join("_", "ABC".Chunked(0, true)));
            Assert.AreEqual("ABCD", String.Join("_", "ABCD".Chunked(0, true)));
            Assert.AreEqual("ABCDE", String.Join("_", "ABCDE".Chunked(0, true)));
            Assert.AreEqual("ABCDEF", String.Join("_", "ABCDEF".Chunked(0, true)));
            Assert.AreEqual("ABCDEFG", String.Join("_", "ABCDEFG".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGH", String.Join("_", "ABCDEFGH".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHI", String.Join("_", "ABCDEFGHI".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJ", String.Join("_", "ABCDEFGHIJ".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJK", String.Join("_", "ABCDEFGHIJK".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJKL", String.Join("_", "ABCDEFGHIJKL".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJKLM", String.Join("_", "ABCDEFGHIJKLM".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJKLMN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJKLMNO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJKLMNOP", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJKLMNOPQ", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJKLMNOPQR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(0, true)));
            Assert.AreEqual("ABCDEFGHIJKLMNOPQRS", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(0, true)));
            Assert.AreEqual("", String.Join("_", "".Chunked(1, true)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(1, true)));
            Assert.AreEqual("A_B", String.Join("_", "AB".Chunked(1, true)));
            Assert.AreEqual("A_B_C", String.Join("_", "ABC".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D", String.Join("_", "ABCD".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E", String.Join("_", "ABCDE".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F", String.Join("_", "ABCDEF".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G", String.Join("_", "ABCDEFG".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H", String.Join("_", "ABCDEFGH".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I", String.Join("_", "ABCDEFGHI".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J", String.Join("_", "ABCDEFGHIJ".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K", String.Join("_", "ABCDEFGHIJK".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L", String.Join("_", "ABCDEFGHIJKL".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M", String.Join("_", "ABCDEFGHIJKLM".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N", String.Join("_", "ABCDEFGHIJKLMN".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O_P", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O_P_Q", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O_P_Q_R", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(1, true)));
            Assert.AreEqual("A_B_C_D_E_F_G_H_I_J_K_L_M_N_O_P_Q_R_S", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(1, true)));
            Assert.AreEqual("", String.Join("_", "".Chunked(2, true)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(2, true)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(2, true)));
            Assert.AreEqual("A_BC", String.Join("_", "ABC".Chunked(2, true)));
            Assert.AreEqual("AB_CD", String.Join("_", "ABCD".Chunked(2, true)));
            Assert.AreEqual("A_BC_DE", String.Join("_", "ABCDE".Chunked(2, true)));
            Assert.AreEqual("AB_CD_EF", String.Join("_", "ABCDEF".Chunked(2, true)));
            Assert.AreEqual("A_BC_DE_FG", String.Join("_", "ABCDEFG".Chunked(2, true)));
            Assert.AreEqual("AB_CD_EF_GH", String.Join("_", "ABCDEFGH".Chunked(2, true)));
            Assert.AreEqual("A_BC_DE_FG_HI", String.Join("_", "ABCDEFGHI".Chunked(2, true)));
            Assert.AreEqual("AB_CD_EF_GH_IJ", String.Join("_", "ABCDEFGHIJ".Chunked(2, true)));
            Assert.AreEqual("A_BC_DE_FG_HI_JK", String.Join("_", "ABCDEFGHIJK".Chunked(2, true)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL", String.Join("_", "ABCDEFGHIJKL".Chunked(2, true)));
            Assert.AreEqual("A_BC_DE_FG_HI_JK_LM", String.Join("_", "ABCDEFGHIJKLM".Chunked(2, true)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(2, true)));
            Assert.AreEqual("A_BC_DE_FG_HI_JK_LM_NO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(2, true)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN_OP", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(2, true)));
            Assert.AreEqual("A_BC_DE_FG_HI_JK_LM_NO_PQ", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(2, true)));
            Assert.AreEqual("AB_CD_EF_GH_IJ_KL_MN_OP_QR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(2, true)));
            Assert.AreEqual("A_BC_DE_FG_HI_JK_LM_NO_PQ_RS", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(2, true)));
            Assert.AreEqual("", String.Join("_", "".Chunked(3, true)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(3, true)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(3, true)));
            Assert.AreEqual("ABC", String.Join("_", "ABC".Chunked(3, true)));
            Assert.AreEqual("A_BCD", String.Join("_", "ABCD".Chunked(3, true)));
            Assert.AreEqual("AB_CDE", String.Join("_", "ABCDE".Chunked(3, true)));
            Assert.AreEqual("ABC_DEF", String.Join("_", "ABCDEF".Chunked(3, true)));
            Assert.AreEqual("A_BCD_EFG", String.Join("_", "ABCDEFG".Chunked(3, true)));
            Assert.AreEqual("AB_CDE_FGH", String.Join("_", "ABCDEFGH".Chunked(3, true)));
            Assert.AreEqual("ABC_DEF_GHI", String.Join("_", "ABCDEFGHI".Chunked(3, true)));
            Assert.AreEqual("A_BCD_EFG_HIJ", String.Join("_", "ABCDEFGHIJ".Chunked(3, true)));
            Assert.AreEqual("AB_CDE_FGH_IJK", String.Join("_", "ABCDEFGHIJK".Chunked(3, true)));
            Assert.AreEqual("ABC_DEF_GHI_JKL", String.Join("_", "ABCDEFGHIJKL".Chunked(3, true)));
            Assert.AreEqual("A_BCD_EFG_HIJ_KLM", String.Join("_", "ABCDEFGHIJKLM".Chunked(3, true)));
            Assert.AreEqual("AB_CDE_FGH_IJK_LMN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(3, true)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_MNO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(3, true)));
            Assert.AreEqual("A_BCD_EFG_HIJ_KLM_NOP", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(3, true)));
            Assert.AreEqual("AB_CDE_FGH_IJK_LMN_OPQ", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(3, true)));
            Assert.AreEqual("ABC_DEF_GHI_JKL_MNO_PQR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(3, true)));
            Assert.AreEqual("A_BCD_EFG_HIJ_KLM_NOP_QRS", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(3, true)));
            Assert.AreEqual("", String.Join("_", "".Chunked(4, true)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(4, true)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(4, true)));
            Assert.AreEqual("ABC", String.Join("_", "ABC".Chunked(4, true)));
            Assert.AreEqual("ABCD", String.Join("_", "ABCD".Chunked(4, true)));
            Assert.AreEqual("A_BCDE", String.Join("_", "ABCDE".Chunked(4, true)));
            Assert.AreEqual("AB_CDEF", String.Join("_", "ABCDEF".Chunked(4, true)));
            Assert.AreEqual("ABC_DEFG", String.Join("_", "ABCDEFG".Chunked(4, true)));
            Assert.AreEqual("ABCD_EFGH", String.Join("_", "ABCDEFGH".Chunked(4, true)));
            Assert.AreEqual("A_BCDE_FGHI", String.Join("_", "ABCDEFGHI".Chunked(4, true)));
            Assert.AreEqual("AB_CDEF_GHIJ", String.Join("_", "ABCDEFGHIJ".Chunked(4, true)));
            Assert.AreEqual("ABC_DEFG_HIJK", String.Join("_", "ABCDEFGHIJK".Chunked(4, true)));
            Assert.AreEqual("ABCD_EFGH_IJKL", String.Join("_", "ABCDEFGHIJKL".Chunked(4, true)));
            Assert.AreEqual("A_BCDE_FGHI_JKLM", String.Join("_", "ABCDEFGHIJKLM".Chunked(4, true)));
            Assert.AreEqual("AB_CDEF_GHIJ_KLMN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(4, true)));
            Assert.AreEqual("ABC_DEFG_HIJK_LMNO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(4, true)));
            Assert.AreEqual("ABCD_EFGH_IJKL_MNOP", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(4, true)));
            Assert.AreEqual("A_BCDE_FGHI_JKLM_NOPQ", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(4, true)));
            Assert.AreEqual("AB_CDEF_GHIJ_KLMN_OPQR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(4, true)));
            Assert.AreEqual("ABC_DEFG_HIJK_LMNO_PQRS", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(4, true)));
            Assert.AreEqual("", String.Join("_", "".Chunked(5, true)));
            Assert.AreEqual("A", String.Join("_", "A".Chunked(5, true)));
            Assert.AreEqual("AB", String.Join("_", "AB".Chunked(5, true)));
            Assert.AreEqual("ABC", String.Join("_", "ABC".Chunked(5, true)));
            Assert.AreEqual("ABCD", String.Join("_", "ABCD".Chunked(5, true)));
            Assert.AreEqual("ABCDE", String.Join("_", "ABCDE".Chunked(5, true)));
            Assert.AreEqual("A_BCDEF", String.Join("_", "ABCDEF".Chunked(5, true)));
            Assert.AreEqual("AB_CDEFG", String.Join("_", "ABCDEFG".Chunked(5, true)));
            Assert.AreEqual("ABC_DEFGH", String.Join("_", "ABCDEFGH".Chunked(5, true)));
            Assert.AreEqual("ABCD_EFGHI", String.Join("_", "ABCDEFGHI".Chunked(5, true)));
            Assert.AreEqual("ABCDE_FGHIJ", String.Join("_", "ABCDEFGHIJ".Chunked(5, true)));
            Assert.AreEqual("A_BCDEF_GHIJK", String.Join("_", "ABCDEFGHIJK".Chunked(5, true)));
            Assert.AreEqual("AB_CDEFG_HIJKL", String.Join("_", "ABCDEFGHIJKL".Chunked(5, true)));
            Assert.AreEqual("ABC_DEFGH_IJKLM", String.Join("_", "ABCDEFGHIJKLM".Chunked(5, true)));
            Assert.AreEqual("ABCD_EFGHI_JKLMN", String.Join("_", "ABCDEFGHIJKLMN".Chunked(5, true)));
            Assert.AreEqual("ABCDE_FGHIJ_KLMNO", String.Join("_", "ABCDEFGHIJKLMNO".Chunked(5, true)));
            Assert.AreEqual("A_BCDEF_GHIJK_LMNOP", String.Join("_", "ABCDEFGHIJKLMNOP".Chunked(5, true)));
            Assert.AreEqual("AB_CDEFG_HIJKL_MNOPQ", String.Join("_", "ABCDEFGHIJKLMNOPQ".Chunked(5, true)));
            Assert.AreEqual("ABC_DEFGH_IJKLM_NOPQR", String.Join("_", "ABCDEFGHIJKLMNOPQR".Chunked(5, true)));
            Assert.AreEqual("ABCD_EFGHI_JKLMN_OPQRS", String.Join("_", "ABCDEFGHIJKLMNOPQRS".Chunked(5, true)));
        }

        [TestMethod]
        public void ToCapitalizedWordsTest()
        {
            Assert.AreEqual(((string)null).ToCapitalizedWords(), null);
            Assert.AreEqual("".ToCapitalizedWords(), "");
            Assert.AreEqual("a".ToCapitalizedWords(), "A");
            Assert.AreEqual("A".ToCapitalizedWords(), "A");
            Assert.AreEqual("ab".ToCapitalizedWords(), "Ab");
            Assert.AreEqual("AB".ToCapitalizedWords(), "AB");
            Assert.AreEqual("AB".ToCapitalizedWords(null, true), "Ab");
            Assert.AreEqual("AB-C".ToCapitalizedWords(null, true), "Ab-c");
            Assert.AreEqual("AB-C".ToCapitalizedWords(null, true, true), "Ab-C");
            Assert.AreEqual("AB CD".ToCapitalizedWords(), "AB CD");
            Assert.AreEqual("AB CD".ToCapitalizedWords(null, true), "Ab Cd");
            Assert.AreEqual("AB CD.EF".ToCapitalizedWords(null, true), "Ab Cd.ef");
            Assert.AreEqual("AB CD.EF".ToCapitalizedWords(null, true, true), "Ab Cd.Ef");
        }

        [TestMethod]
        public void ToAsciiStringTest()
        {
            Assert.AreEqual(((string)null).ToAsciiString(32, 127, '?'), null);
            Assert.AreEqual("".ToAsciiString(32, 127, '?'), "");
            Assert.AreEqual("Cérémony".ToAsciiString(32, 127, '?'), "C?r?mony");
        }
    }
}
